# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-12 07:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0002_teacher_profession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='profession',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='edu.Course'),
        ),
    ]
